[package]
name = "hgrep_assets"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syntect = "5.0"
bincode = "1.3"
flate2 = "1"
path-slash = "0.2"
