name: Weekly check
on:
  schedule:
    # Every Saturday 10:21 in JST
    - cron: '21 2 * * 6'
  workflow_dispatch:

jobs:
  cargo-install:
    runs-on: ubuntu-latest
    steps:
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo install --color always hgrep
      - run: hgrep --version
